version: '3'
services:
  web:
    image: nginx:alpine
    container_name: safe-cam-site
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

